name: smart_cloud
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.7  # Asegúrate de usar la última versión
  firebase_auth: ^5.5.3     # Asegúrate de usar la última 
  firebase_core: ^3.13.0
  logging: ^1.3.0           # Asegúrate de usar la última versión

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true